# Generated by Django 5.1.7 on 2025-03-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_options_todo_description_todo_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluido', 'Concluido')], default='Pendente', max_length=10, verbose_name='Status'),
        ),
    ]
